business logic for quantity update and deletion of product
PremiyaR/Inventory-Management-System-pharmacy pull request #1
Opened 2024-03-15 09:10 UTC by PremiyaR

2024-03-17 10:00 UTC, badCODERever commented on inventory/src/main/java/com/pilot/inventory/controller/UsersController.java
> +import org.springframework.web.bind.annotation.*;
remove wildcard operator and import only required classes

2024-03-17 10:01 UTC, badCODERever commented on inventory/src/main/java/com/pilot/inventory/controller/UsersController.java
>  @RequestMapping("/users")
Better to use constants and (can create new constant class to maintain all the REST constants)

2024-03-17 10:05 UTC, badCODERever requested changes

2024-03-17 10:05 UTC, badCODERever commented on inventory/src/main/java/com/pilot/inventory/model/entity/Categories.java
>  import jakarta.persistence.*;
remove wildcard operator use only required class

2024-03-17 10:05 UTC, badCODERever commented on inventory/src/main/java/com/pilot/inventory/model/entity/Product.java
> -    @JoinColumn(nullable = false,name = "category_id")
why is one is removed?

2024-03-17 10:05 UTC, badCODERever commented on inventory/src/main/java/com/pilot/inventory/service/OrdersServiceImpl.java
> -            status="Product not deleted,Please check your id is valid";
Could you please explain, this block of code required?

2024-03-18 04:45 UTC, PremiyaR commented on inventory/src/main/java/com/pilot/inventory/service/OrdersServiceImpl.java
> -            status="Product not deleted,Please check your id is valid";
If the given ID doesn't exist, the row cannot be found and deleted. Hence why I wrote this code.

2024-03-18 09:01 UTC, PremiyaR commented on inventory/src/main/java/com/pilot/inventory/model/entity/Product.java
> -    @JoinColumn(nullable = false,name = "category_id")
I encountered an error in between, so I tried removing it. Forgot to add it back.

2024-04-03 09:39 UTC, merged